name: Svelte CI

on:
  push:
    paths:
      - 'app_js/**'
  pull_request:
    paths:
      - 'app_js/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      working-directory: app_js
      run: npm install

        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Lint code
      working-directory: app_js
      run: npm run lint

    - name: Run Tests
      working-directory: app_js
      run: npm test

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: app_js
        file: app_js/Dockerfile
        push: true
        tags: relisqu/svelte-app:latest
